sudo: false
dist: trusty

language: node_js
os:
  - linux
  - osx
node_js:
  - 8
  - 10

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TRAVIS_OS_NAME" == "linux" ]]; then mv .npmrc _npmrc; fi
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm i; fi
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint; fi
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm run check; fi

script:
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm run cover; else npm t; fi

after_script:
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

notifications:
  email: false
