sudo: false
dist: trusty

language: node_js
os:
  - linux
  - osx
node_js:
  - 8
  - node

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_NODE_VERSION" == "8" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint; fi
  - if [[ "$TRAVIS_NODE_VERSION" == "8" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm run check; fi

install:
  - npm i --no-package-lock

script:
  - if [[ "$TRAVIS_NODE_VERSION" == "8" && "$TRAVIS_OS_NAME" == "linux" ]]; then npm run cover; else npm t; fi

after_script:
  - if [[ "$TRAVIS_NODE_VERSION" == "8" && "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

notifications:
  email: false

branches:
  only:
    - master