environment:
  matrix:
    - nodejs_version: "8"
    #- nodejs_version: "9" // no node9 support yet

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i --no-optional --no-package-lock

test_script:
  - npm t

build: off

branches:
  only:
    - master